name: rxvault
description: "RxVault"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.0.18
  http: ^1.2.1
  dio: ^5.0.1
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  lottie: ^3.1.0
  #  flutter_native_splash: ^2.2.19
  share: ^2.0.4
  path: any
  image_picker: ^1.1.1
  intl: '>=0.17.0 <1.0.0'
  meta: '>=1.8.0 <2.0.0'
  photo_view: ^0.15.0
  file_picker: ^8.0.3
  image_cropper: ^6.0.0
  flutter_svg: ^2.0.10+1
  image_picker_web: ^4.0.0
  universal_html: ^2.2.4
  flutter_cors: ^1.5.0
  pdf: ^3.10.8
  printing: ^5.12.0
  fl_chart: ^0.68.0
  card_swiper: ^3.0.1


dev_dependencies:
  dart_code_metrics: ^4.19.2

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500

    - family: RxIcons
      fonts:
        - asset: assets/fonts/RxIcons.ttf



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#5a81fa"
    theme_color: "#5a81fa"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"






