// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByuDyXcyQbE8kL5O9E9_-bPutee5r8tW8',
    appId: '1:47584927433:web:006c2be2328d08ef567718',
    messagingSenderId: '47584927433',
    projectId: 'rxvault-b0bd0',
    authDomain: 'rxvault-b0bd0.firebaseapp.com',
    storageBucket: 'rxvault-b0bd0.appspot.com',
    measurementId: 'G-P5QBG7301R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5E7JwQrJESeSuyYE3cIF31GYuH4LKdk',
    appId: '1:47584927433:android:acc327c11f85c8f0567718',
    messagingSenderId: '47584927433',
    projectId: 'rxvault-b0bd0',
    storageBucket: 'rxvault-b0bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABW3EPu7GBVtCkYBg-ACLFKAbKofZZHdo',
    appId: '1:47584927433:ios:79eb1bb46e6faef7567718',
    messagingSenderId: '47584927433',
    projectId: 'rxvault-b0bd0',
    storageBucket: 'rxvault-b0bd0.appspot.com',
    iosBundleId: 'com.ensivo.rxvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABW3EPu7GBVtCkYBg-ACLFKAbKofZZHdo',
    appId: '1:47584927433:ios:79eb1bb46e6faef7567718',
    messagingSenderId: '47584927433',
    projectId: 'rxvault-b0bd0',
    storageBucket: 'rxvault-b0bd0.appspot.com',
    iosBundleId: 'com.ensivo.rxvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByuDyXcyQbE8kL5O9E9_-bPutee5r8tW8',
    appId: '1:47584927433:web:9270c4f1bce75ec9567718',
    messagingSenderId: '47584927433',
    projectId: 'rxvault-b0bd0',
    authDomain: 'rxvault-b0bd0.firebaseapp.com',
    storageBucket: 'rxvault-b0bd0.appspot.com',
    measurementId: 'G-BQJTSFJDLX',
  );

}